# This is a basic workflow to help you get started with Actions
# Ref: https://stackoverflow.com/a/69465861/3016570

name: Get GPT2

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 2,14 * * *"
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Use hashes for extra security - https://stackoverflow.com/a/70196496/3016570
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      
      - name: Run specific commands # Another step name
        run: |
          wget -O checkpoint_Multichannel_SgVideosArticles_titles_keywords_v3_800_355.tar https://www.dropbox.com/s/89jezt9ykajumae/checkpoint_Multichannel_SgVideosArticles_titles_keywords_v3_800_355.tar?dl=0
          echo "DOwnload with wget"
      
      - name: Run specific commands # Another step name
        run: |
          tar -xvf checkpoint_Multichannel_SgVideosArticles_titles_keywords_v3_800_355.tar 
          echo "Extract"
      
      - name: Push Changes Back To Repo
        uses: GuillaumeFalourd/git-commit-push@0363e474c79afd69c7e295d331183c0c1d824619
