# This is a basic workflow to help you get started with Actions
# Ref: https://stackoverflow.com/a/69465861/3016570

name: Get GPT2

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 1 * * *"
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      - name: Run specific commands # Another step name
        run: |
          wget -O checkpoint_Multichannel_SgVideosArticles_titles_keywords_v3_800_355.tar https://www.dropbox.com/s/89jezt9ykajumae/checkpoint_Multichannel_SgVideosArticles_titles_keywords_v3_800_355.tar?dl=0
          echo "Download with wget"
      
      - name: Run specific commands # Another step name
        run: |
          tar -xvf checkpoint_Multichannel_SgVideosArticles_titles_keywords_v3_800_355.tar 
          echo "Extract tar file"
      
      - name: Install dependencies
        run: |
          pip install gpt-2-simple
          
      - name: Execute Python script # Run the app.py
        run: python main.py
        
      - name: Run specific commands # Another step name
        run: |
          cat gpt2_gentext.txt
          echo "Show the output"
